rpc_server:
  host: 0.0.0.0
  port: 8289
http_server:
  host: 0.0.0.0
  port: 8188

chains:
  - chain_name: "Bitcoin"
    chain_id: "DappLinkBitcoin"
    netword: mainnet
  - chain_name: "Ethereum"
    chain_id: "DappLinkEthereum"
    netword: mainnet
  - chain_name: "Solana"
    chain_id: "DappLinkSolana"
    netword: mainnet
  - chain_name: "Tron"
    chain_id: "DappLinkTron"
    netword: mainnet
  - chain_name: "Bnb"
    chain_id: "DappLinkBnbChain"
    netword: mainnet

wallet_node:
  eth:
    rpc_url: 'https://go.getblock.asia/a4d6de8f9d76477da58738bfa8c3b029'
    rpc_user: ''
    rpc_pass: ''
    data_api_url: 'https://api-holesky.etherscan.io/api?'
    data_api_key: 'HZEZGEPJJDA633N421AYW9NE8JFNZZC7JT'
    data_api_token: ''
    time_out: 15

  bnb:
    rpc_url: 'https://shared.ap-southeast-1.getblock.io/cd2737b83bed4b529f2b29001024b1b8'
    rpc_user: ''
    rpc_pass: ''
    data_api_url: 'https://api.etherscan.io/api?'
    data_api_key: 'HZEZGEPJJDA633N421AYW9NE8JFNZZC7JT'
    data_api_token: ''
    contract_addr: ["0x55d398326f99059fF775485246999027B3197955", "0xbCfd4808CCF4Bdf7A61352e2762D2d4D0Bd455e1"]
    time_out: 15
    aa:
      enabled: true
      entry_point: "0x0000000000000000000000000000000000000000"
      delegate: "0x0000000000000000000000000000000000000000"
      paymaster: "0x0000000000000000000000000000000000000000"
      sponsor_address: "0x0000000000000000000000000000000000000000"
      chain_id_numeric: "56"

  btc:
    rpc_url: 'bitcoin-mainnet.core.chainstack.com'
    rpc_user: 'objective-colden'
    rpc_pass: 'plank-scored-lying-duty-lazily-smudge'
    data_api_url: 'https://www.oklink.com/'
    data_api_key: '5181d535-b68f-41cf-bbc6-25905e46b6a6'
    data_api_token: ''
    time_out: 100
    tp_api_url: 'https://blockchain.info/'

  solana:
    rpc_url: 'https://go.getblock.io/70f479b9ed834b5f96a26934e0492b36'
    rpc_user: ''
    rpc_pass: ''
    data_api_url: 'https://public-api.solscan.io'
    data_api_key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVkQXQiOjE3MjQwNjIxMzk5MDYsImVtYWlsIjoiemFja2d1by5ndW9AZ21haWwuY29tIiwiYWN0aW9uIjoidG9rZW4tYXBpIiwiYXBpVmVyc2lvbiI6InYxIiwiaWF0IjoxNzI0MDYyMTM5fQ.EaWDC25lyGNx_LqRL5sAYYKLMbq10brnexKnAz9C3UY'
    data_api_token: ''
    time_out: 15

  tron:
    rpc_url: 'https://api.trongrid.io'
    rpc_user: 'TRON-PRO-API-KEY'
    rpc_pass: 'f7ae3e01-17d1-4a31-92b3-57f99457d915'
    data_api_url: 'https://www.oklink.com'
    data_api_key: '5181d535-b68f-41cf-bbc6-25905e46b6a6'
    data_api_token: ''
    time_out: 15
    sponsor:
      activation_transfer_sun: 100000
      delegate_balance_sun: 1000000000
      estimated_energy: 150000
      justlend_contract: "TU2MJ5Veik1LRAgjeSzEdvmDYx7mefJZvd"

network: mainnet
enable_api_cache: false
access_token: "DappLinkTheWeb3202402290001"

