// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: protobuf/wallet-api.proto

package wallet_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReturnCode int32

const (
	ReturnCode_SUCCESS ReturnCode = 0
	ReturnCode_ERROR   ReturnCode = 1
)

// Enum value maps for ReturnCode.
var (
	ReturnCode_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR",
	}
	ReturnCode_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   1,
	}
)

func (x ReturnCode) Enum() *ReturnCode {
	p := new(ReturnCode)
	*p = x
	return p
}

func (x ReturnCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_wallet_api_proto_enumTypes[0].Descriptor()
}

func (ReturnCode) Type() protoreflect.EnumType {
	return &file_protobuf_wallet_api_proto_enumTypes[0]
}

func (x ReturnCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnCode.Descriptor instead.
func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_wallet_api_proto_rawDescGZIP(), []int{0}
}

type TxStatus int32

const (
	TxStatus_NotFound TxStatus = 0
	TxStatus_Pending  TxStatus = 1
	TxStatus_Failed   TxStatus = 2
	TxStatus_Success  TxStatus = 3
	TxStatus_Other    TxStatus = 4
)

// Enum value maps for TxStatus.
var (
	TxStatus_name = map[int32]string{
		0: "NotFound",
		1: "Pending",
		2: "Failed",
		3: "Success",
		4: "Other",
	}
	TxStatus_value = map[string]int32{
		"NotFound": 0,
		"Pending":  1,
		"Failed":   2,
		"Success":  3,
		"Other":    4,
	}
)

func (x TxStatus) Enum() *TxStatus {
	p := new(TxStatus)
	*p = x
	return p
}

func (x TxStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_wallet_api_proto_enumTypes[1].Descriptor()
}

func (TxStatus) Type() protoreflect.EnumType {
	return &file_protobuf_wallet_api_proto_enumTypes[1]
}

func (x TxStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxStatus.Descriptor instead.
func (TxStatus) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_wallet_api_proto_rawDescGZIP(), []int{1}
}

type EndPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndPoint) Reset() {
	*x = EndPoint{}
	mi := &file_protobuf_wallet_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndPoint) ProtoMessage() {}

func (x *EndPoint) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_wallet_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndPoint.ProtoReflect.Descriptor instead.
func (*EndPoint) Descriptor() ([]byte, []int) {
	return file_protobuf_wallet_api_proto_rawDescGZIP(), []int{0}
}

func (x *EndPoint) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SupportChain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainName     string                 `protobuf:"bytes,1,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Network       string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	EndPoint      []*EndPoint            `protobuf:"bytes,4,rep,name=end_point,json=endPoint,proto3" json:"end_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportChain) Reset() {
	*x = SupportChain{}
	mi := &file_protobuf_wallet_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportChain) ProtoMessage() {}

func (x *SupportChain) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_wallet_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportChain.ProtoReflect.Descriptor instead.
func (*SupportChain) Descriptor() ([]byte, []int) {
	return file_protobuf_wallet_api_proto_rawDescGZIP(), []int{1}
}

func (x *SupportChain) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *SupportChain) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *SupportChain) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *SupportChain) GetEndPoint() []*EndPoint {
	if x != nil {
		return x.EndPoint
	}
	return nil
}

type SupportChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportChainRequest) Reset() {
	*x = SupportChainRequest{}
	mi := &file_protobuf_wallet_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportChainRequest) ProtoMessage() {}

func (x *SupportChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_wallet_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportChainRequest.ProtoReflect.Descriptor instead.
func (*SupportChainRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_wallet_api_proto_rawDescGZIP(), []int{2}
}

func (x *SupportChainRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

type SupportChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ReturnCode             `protobuf:"varint,1,opt,name=code,proto3,enum=ReturnCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Chains        []*SupportChain        `protobuf:"bytes,3,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportChainResponse) Reset() {
	*x = SupportChainResponse{}
	mi := &file_protobuf_wallet_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportChainResponse) ProtoMessage() {}

func (x *SupportChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_wallet_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportChainResponse.ProtoReflect.Descriptor instead.
func (*SupportChainResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_wallet_api_proto_rawDescGZIP(), []int{3}
}

func (x *SupportChainResponse) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_SUCCESS
}

func (x *SupportChainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SupportChainResponse) GetChains() []*SupportChain {
	if x != nil {
		return x.Chains
	}
	return nil
}

var File_protobuf_wallet_api_proto protoreflect.FileDescriptor

const file_protobuf_wallet_api_proto_rawDesc = "" +
	"\n" +
	"\x19protobuf/wallet-api.proto\"\x1c\n" +
	"\bEndPoint\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x8a\x01\n" +
	"\fSupportChain\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x01 \x01(\tR\tchainName\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12&\n" +
	"\tend_point\x18\x04 \x03(\v2\t.EndPointR\bendPoint\"<\n" +
	"\x13SupportChainRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\"x\n" +
	"\x14SupportChainResponse\x12\x1f\n" +
	"\x04code\x18\x01 \x01(\x0e2\v.ReturnCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x06chains\x18\x03 \x03(\v2\r.SupportChainR\x06chains*$\n" +
	"\n" +
	"ReturnCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01*I\n" +
	"\bTxStatus\x12\f\n" +
	"\bNotFound\x10\x00\x12\v\n" +
	"\aPending\x10\x01\x12\n" +
	"\n" +
	"\x06Failed\x10\x02\x12\v\n" +
	"\aSuccess\x10\x03\x12\t\n" +
	"\x05Other\x10\x042\\\n" +
	"\x17WalletApiGateWayService\x12A\n" +
	"\x10getSupportChains\x12\x14.SupportChainRequest\x1a\x15.SupportChainResponse\"\x00B\x17Z\x15./protobuf/wallet-apib\x06proto3"

var (
	file_protobuf_wallet_api_proto_rawDescOnce sync.Once
	file_protobuf_wallet_api_proto_rawDescData []byte
)

func file_protobuf_wallet_api_proto_rawDescGZIP() []byte {
	file_protobuf_wallet_api_proto_rawDescOnce.Do(func() {
		file_protobuf_wallet_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_wallet_api_proto_rawDesc), len(file_protobuf_wallet_api_proto_rawDesc)))
	})
	return file_protobuf_wallet_api_proto_rawDescData
}

var file_protobuf_wallet_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobuf_wallet_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_wallet_api_proto_goTypes = []any{
	(ReturnCode)(0),              // 0: ReturnCode
	(TxStatus)(0),                // 1: TxStatus
	(*EndPoint)(nil),             // 2: EndPoint
	(*SupportChain)(nil),         // 3: SupportChain
	(*SupportChainRequest)(nil),  // 4: SupportChainRequest
	(*SupportChainResponse)(nil), // 5: SupportChainResponse
}
var file_protobuf_wallet_api_proto_depIdxs = []int32{
	2, // 0: SupportChain.end_point:type_name -> EndPoint
	0, // 1: SupportChainResponse.code:type_name -> ReturnCode
	3, // 2: SupportChainResponse.chains:type_name -> SupportChain
	4, // 3: WalletApiGateWayService.getSupportChains:input_type -> SupportChainRequest
	5, // 4: WalletApiGateWayService.getSupportChains:output_type -> SupportChainResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_wallet_api_proto_init() }
func file_protobuf_wallet_api_proto_init() {
	if File_protobuf_wallet_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_wallet_api_proto_rawDesc), len(file_protobuf_wallet_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_wallet_api_proto_goTypes,
		DependencyIndexes: file_protobuf_wallet_api_proto_depIdxs,
		EnumInfos:         file_protobuf_wallet_api_proto_enumTypes,
		MessageInfos:      file_protobuf_wallet_api_proto_msgTypes,
	}.Build()
	File_protobuf_wallet_api_proto = out.File
	file_protobuf_wallet_api_proto_goTypes = nil
	file_protobuf_wallet_api_proto_depIdxs = nil
}
