// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: protobuf/wallet-api.proto

package wallet_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WalletApiGateWayService_GetSupportChains_FullMethodName = "/WalletApiGateWayService/getSupportChains"
)

// WalletApiGateWayServiceClient is the client API for WalletApiGateWayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletApiGateWayServiceClient interface {
	GetSupportChains(ctx context.Context, in *SupportChainRequest, opts ...grpc.CallOption) (*SupportChainResponse, error)
}

type walletApiGateWayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletApiGateWayServiceClient(cc grpc.ClientConnInterface) WalletApiGateWayServiceClient {
	return &walletApiGateWayServiceClient{cc}
}

func (c *walletApiGateWayServiceClient) GetSupportChains(ctx context.Context, in *SupportChainRequest, opts ...grpc.CallOption) (*SupportChainResponse, error) {
	out := new(SupportChainResponse)
	err := c.cc.Invoke(ctx, WalletApiGateWayService_GetSupportChains_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletApiGateWayServiceServer is the server API for WalletApiGateWayService service.
// All implementations should embed UnimplementedWalletApiGateWayServiceServer
// for forward compatibility
type WalletApiGateWayServiceServer interface {
	GetSupportChains(context.Context, *SupportChainRequest) (*SupportChainResponse, error)
}

// UnimplementedWalletApiGateWayServiceServer should be embedded to have forward compatible implementations.
type UnimplementedWalletApiGateWayServiceServer struct {
}

func (UnimplementedWalletApiGateWayServiceServer) GetSupportChains(context.Context, *SupportChainRequest) (*SupportChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportChains not implemented")
}

// UnsafeWalletApiGateWayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletApiGateWayServiceServer will
// result in compilation errors.
type UnsafeWalletApiGateWayServiceServer interface {
	mustEmbedUnimplementedWalletApiGateWayServiceServer()
}

func RegisterWalletApiGateWayServiceServer(s grpc.ServiceRegistrar, srv WalletApiGateWayServiceServer) {
	s.RegisterService(&WalletApiGateWayService_ServiceDesc, srv)
}

func _WalletApiGateWayService_GetSupportChains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletApiGateWayServiceServer).GetSupportChains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletApiGateWayService_GetSupportChains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletApiGateWayServiceServer).GetSupportChains(ctx, req.(*SupportChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletApiGateWayService_ServiceDesc is the grpc.ServiceDesc for WalletApiGateWayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletApiGateWayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WalletApiGateWayService",
	HandlerType: (*WalletApiGateWayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getSupportChains",
			Handler:    _WalletApiGateWayService_GetSupportChains_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/wallet-api.proto",
}
