// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: dapplink/walletsign.proto

package walletsign

import (
	"github.com/dapplink-labs/dapplink-wallet-api/protobuf/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainSignMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Network       string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	AssetType     string                 `protobuf:"bytes,4,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainSignMethodRequest) Reset() {
	*x = ChainSignMethodRequest{}
	mi := &file_dapplink_walletsign_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainSignMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainSignMethodRequest) ProtoMessage() {}

func (x *ChainSignMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainSignMethodRequest.ProtoReflect.Descriptor instead.
func (*ChainSignMethodRequest) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{0}
}

func (x *ChainSignMethodRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *ChainSignMethodRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ChainSignMethodRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ChainSignMethodRequest) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

type ChainSignMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          common.ReturnCode      `protobuf:"varint,1,opt,name=code,proto3,enum=dapplink.ReturnCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SignMethod    string                 `protobuf:"bytes,3,opt,name=sign_method,json=signMethod,proto3" json:"sign_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainSignMethodResponse) Reset() {
	*x = ChainSignMethodResponse{}
	mi := &file_dapplink_walletsign_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainSignMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainSignMethodResponse) ProtoMessage() {}

func (x *ChainSignMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainSignMethodResponse.ProtoReflect.Descriptor instead.
func (*ChainSignMethodResponse) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{1}
}

func (x *ChainSignMethodResponse) GetCode() common.ReturnCode {
	if x != nil {
		return x.Code
	}
	return common.ReturnCode(0)
}

func (x *ChainSignMethodResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChainSignMethodResponse) GetSignMethod() string {
	if x != nil {
		return x.SignMethod
	}
	return ""
}

type ChainSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Network       string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	AssetType     string                 `protobuf:"bytes,4,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainSchemaRequest) Reset() {
	*x = ChainSchemaRequest{}
	mi := &file_dapplink_walletsign_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainSchemaRequest) ProtoMessage() {}

func (x *ChainSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainSchemaRequest.ProtoReflect.Descriptor instead.
func (*ChainSchemaRequest) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{2}
}

func (x *ChainSchemaRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *ChainSchemaRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ChainSchemaRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ChainSchemaRequest) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

type ChainSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          common.ReturnCode      `protobuf:"varint,1,opt,name=code,proto3,enum=dapplink.ReturnCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Schema        string                 `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainSchemaResponse) Reset() {
	*x = ChainSchemaResponse{}
	mi := &file_dapplink_walletsign_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainSchemaResponse) ProtoMessage() {}

func (x *ChainSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainSchemaResponse.ProtoReflect.Descriptor instead.
func (*ChainSchemaResponse) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{3}
}

func (x *ChainSchemaResponse) GetCode() common.ReturnCode {
	if x != nil {
		return x.Code
	}
	return common.ReturnCode(0)
}

func (x *ChainSchemaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChainSchemaResponse) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type ExportPublicKey struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicKey         string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	CompressPublicKey string                 `protobuf:"bytes,2,opt,name=compress_public_key,json=compressPublicKey,proto3" json:"compress_public_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExportPublicKey) Reset() {
	*x = ExportPublicKey{}
	mi := &file_dapplink_walletsign_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPublicKey) ProtoMessage() {}

func (x *ExportPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPublicKey.ProtoReflect.Descriptor instead.
func (*ExportPublicKey) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{4}
}

func (x *ExportPublicKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ExportPublicKey) GetCompressPublicKey() string {
	if x != nil {
		return x.CompressPublicKey
	}
	return ""
}

type CreateKeyPairAndExportPublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Network       string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	KeyNum        uint64                 `protobuf:"varint,4,opt,name=key_num,json=keyNum,proto3" json:"key_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyPairAndExportPublicKeyRequest) Reset() {
	*x = CreateKeyPairAndExportPublicKeyRequest{}
	mi := &file_dapplink_walletsign_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyPairAndExportPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyPairAndExportPublicKeyRequest) ProtoMessage() {}

func (x *CreateKeyPairAndExportPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyPairAndExportPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateKeyPairAndExportPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{5}
}

func (x *CreateKeyPairAndExportPublicKeyRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *CreateKeyPairAndExportPublicKeyRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *CreateKeyPairAndExportPublicKeyRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *CreateKeyPairAndExportPublicKeyRequest) GetKeyNum() uint64 {
	if x != nil {
		return x.KeyNum
	}
	return 0
}

type CreateKeyPairAndExportPublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          common.ReturnCode      `protobuf:"varint,1,opt,name=code,proto3,enum=dapplink.ReturnCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PublicKeyList []*ExportPublicKey     `protobuf:"bytes,3,rep,name=public_key_list,json=publicKeyList,proto3" json:"public_key_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyPairAndExportPublicKeyResponse) Reset() {
	*x = CreateKeyPairAndExportPublicKeyResponse{}
	mi := &file_dapplink_walletsign_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyPairAndExportPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyPairAndExportPublicKeyResponse) ProtoMessage() {}

func (x *CreateKeyPairAndExportPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyPairAndExportPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateKeyPairAndExportPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{6}
}

func (x *CreateKeyPairAndExportPublicKeyResponse) GetCode() common.ReturnCode {
	if x != nil {
		return x.Code
	}
	return common.ReturnCode(0)
}

func (x *CreateKeyPairAndExportPublicKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateKeyPairAndExportPublicKeyResponse) GetPublicKeyList() []*ExportPublicKey {
	if x != nil {
		return x.PublicKeyList
	}
	return nil
}

type ExportPublicKeyWithAddress struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicKey         string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	CompressPublicKey string                 `protobuf:"bytes,2,opt,name=compress_public_key,json=compressPublicKey,proto3" json:"compress_public_key,omitempty"`
	Address           string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExportPublicKeyWithAddress) Reset() {
	*x = ExportPublicKeyWithAddress{}
	mi := &file_dapplink_walletsign_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPublicKeyWithAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPublicKeyWithAddress) ProtoMessage() {}

func (x *ExportPublicKeyWithAddress) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPublicKeyWithAddress.ProtoReflect.Descriptor instead.
func (*ExportPublicKeyWithAddress) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{7}
}

func (x *ExportPublicKeyWithAddress) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ExportPublicKeyWithAddress) GetCompressPublicKey() string {
	if x != nil {
		return x.CompressPublicKey
	}
	return ""
}

func (x *ExportPublicKeyWithAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateKeyPairsWithAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Network       string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	AddressFormat string                 `protobuf:"bytes,4,opt,name=address_format,json=addressFormat,proto3" json:"address_format,omitempty"`
	KeyNum        uint64                 `protobuf:"varint,5,opt,name=key_num,json=keyNum,proto3" json:"key_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyPairsWithAddressesRequest) Reset() {
	*x = CreateKeyPairsWithAddressesRequest{}
	mi := &file_dapplink_walletsign_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyPairsWithAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyPairsWithAddressesRequest) ProtoMessage() {}

func (x *CreateKeyPairsWithAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyPairsWithAddressesRequest.ProtoReflect.Descriptor instead.
func (*CreateKeyPairsWithAddressesRequest) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{8}
}

func (x *CreateKeyPairsWithAddressesRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *CreateKeyPairsWithAddressesRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *CreateKeyPairsWithAddressesRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *CreateKeyPairsWithAddressesRequest) GetAddressFormat() string {
	if x != nil {
		return x.AddressFormat
	}
	return ""
}

func (x *CreateKeyPairsWithAddressesRequest) GetKeyNum() uint64 {
	if x != nil {
		return x.KeyNum
	}
	return 0
}

type CreateKeyPairsWithAddressesResponse struct {
	state              protoimpl.MessageState        `protogen:"open.v1"`
	Code               common.ReturnCode             `protobuf:"varint,1,opt,name=code,proto3,enum=dapplink.ReturnCode" json:"code,omitempty"`
	Message            string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PublicKeyAddresses []*ExportPublicKeyWithAddress `protobuf:"bytes,3,rep,name=public_key_addresses,json=publicKeyAddresses,proto3" json:"public_key_addresses,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateKeyPairsWithAddressesResponse) Reset() {
	*x = CreateKeyPairsWithAddressesResponse{}
	mi := &file_dapplink_walletsign_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyPairsWithAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyPairsWithAddressesResponse) ProtoMessage() {}

func (x *CreateKeyPairsWithAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyPairsWithAddressesResponse.ProtoReflect.Descriptor instead.
func (*CreateKeyPairsWithAddressesResponse) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{9}
}

func (x *CreateKeyPairsWithAddressesResponse) GetCode() common.ReturnCode {
	if x != nil {
		return x.Code
	}
	return common.ReturnCode(0)
}

func (x *CreateKeyPairsWithAddressesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateKeyPairsWithAddressesResponse) GetPublicKeyAddresses() []*ExportPublicKeyWithAddress {
	if x != nil {
		return x.PublicKeyAddresses
	}
	return nil
}

type TransactionBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FromAddress   string                 `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress     string                 `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,5,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionBody) Reset() {
	*x = TransactionBody{}
	mi := &file_dapplink_walletsign_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionBody) ProtoMessage() {}

func (x *TransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionBody.ProtoReflect.Descriptor instead.
func (*TransactionBody) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{10}
}

func (x *TransactionBody) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TransactionBody) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *TransactionBody) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *TransactionBody) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransactionBody) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

type SignTransactionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MessageHash   string                 `protobuf:"bytes,2,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	RiskKeyHash   string                 `protobuf:"bytes,3,opt,name=risk_key_hash,json=riskKeyHash,proto3" json:"risk_key_hash,omitempty"`
	WalletKeyHash string                 `protobuf:"bytes,4,opt,name=wallet_key_hash,json=walletKeyHash,proto3" json:"wallet_key_hash,omitempty"`
	TxBody        *TransactionBody       `protobuf:"bytes,5,opt,name=tx_body,json=txBody,proto3" json:"tx_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTransactionMessage) Reset() {
	*x = SignTransactionMessage{}
	mi := &file_dapplink_walletsign_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionMessage) ProtoMessage() {}

func (x *SignTransactionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionMessage.ProtoReflect.Descriptor instead.
func (*SignTransactionMessage) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{11}
}

func (x *SignTransactionMessage) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SignTransactionMessage) GetMessageHash() string {
	if x != nil {
		return x.MessageHash
	}
	return ""
}

func (x *SignTransactionMessage) GetRiskKeyHash() string {
	if x != nil {
		return x.RiskKeyHash
	}
	return ""
}

func (x *SignTransactionMessage) GetWalletKeyHash() string {
	if x != nil {
		return x.WalletKeyHash
	}
	return ""
}

func (x *SignTransactionMessage) GetTxBody() *TransactionBody {
	if x != nil {
		return x.TxBody
	}
	return nil
}

type SignTransactionsMessageRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ConsumerToken string                    `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	ChainId       string                    `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Network       string                    `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	SignTxnMsg    []*SignTransactionMessage `protobuf:"bytes,4,rep,name=sign_txn_msg,json=signTxnMsg,proto3" json:"sign_txn_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTransactionsMessageRequest) Reset() {
	*x = SignTransactionsMessageRequest{}
	mi := &file_dapplink_walletsign_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionsMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionsMessageRequest) ProtoMessage() {}

func (x *SignTransactionsMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionsMessageRequest.ProtoReflect.Descriptor instead.
func (*SignTransactionsMessageRequest) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{12}
}

func (x *SignTransactionsMessageRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *SignTransactionsMessageRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *SignTransactionsMessageRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *SignTransactionsMessageRequest) GetSignTxnMsg() []*SignTransactionMessage {
	if x != nil {
		return x.SignTxnMsg
	}
	return nil
}

type MsgWithSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageHash   string                 `protobuf:"bytes,1,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	IsSuccess     bool                   `protobuf:"varint,3,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgWithSignature) Reset() {
	*x = MsgWithSignature{}
	mi := &file_dapplink_walletsign_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgWithSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgWithSignature) ProtoMessage() {}

func (x *MsgWithSignature) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgWithSignature.ProtoReflect.Descriptor instead.
func (*MsgWithSignature) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{13}
}

func (x *MsgWithSignature) GetMessageHash() string {
	if x != nil {
		return x.MessageHash
	}
	return ""
}

func (x *MsgWithSignature) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *MsgWithSignature) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type SignTransactionsMessageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             common.ReturnCode      `protobuf:"varint,1,opt,name=Code,proto3,enum=dapplink.ReturnCode" json:"Code,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Signature        string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	MsgWithSignature []*MsgWithSignature    `protobuf:"bytes,4,rep,name=msg_with_signature,json=msgWithSignature,proto3" json:"msg_with_signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignTransactionsMessageResponse) Reset() {
	*x = SignTransactionsMessageResponse{}
	mi := &file_dapplink_walletsign_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionsMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionsMessageResponse) ProtoMessage() {}

func (x *SignTransactionsMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionsMessageResponse.ProtoReflect.Descriptor instead.
func (*SignTransactionsMessageResponse) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{14}
}

func (x *SignTransactionsMessageResponse) GetCode() common.ReturnCode {
	if x != nil {
		return x.Code
	}
	return common.ReturnCode(0)
}

func (x *SignTransactionsMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignTransactionsMessageResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignTransactionsMessageResponse) GetMsgWithSignature() []*MsgWithSignature {
	if x != nil {
		return x.MsgWithSignature
	}
	return nil
}

type TransactionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	WalletKeyHash string                 `protobuf:"bytes,2,opt,name=wallet_key_hash,json=walletKeyHash,proto3" json:"wallet_key_hash,omitempty"`
	RiskKeyHash   string                 `protobuf:"bytes,3,opt,name=risk_key_hash,json=riskKeyHash,proto3" json:"risk_key_hash,omitempty"`
	TxBase64Body  string                 `protobuf:"bytes,4,opt,name=tx_base64_body,json=txBase64Body,proto3" json:"tx_base64_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionMessage) Reset() {
	*x = TransactionMessage{}
	mi := &file_dapplink_walletsign_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMessage) ProtoMessage() {}

func (x *TransactionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMessage.ProtoReflect.Descriptor instead.
func (*TransactionMessage) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{15}
}

func (x *TransactionMessage) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *TransactionMessage) GetWalletKeyHash() string {
	if x != nil {
		return x.WalletKeyHash
	}
	return ""
}

func (x *TransactionMessage) GetRiskKeyHash() string {
	if x != nil {
		return x.RiskKeyHash
	}
	return ""
}

func (x *TransactionMessage) GetTxBase64Body() string {
	if x != nil {
		return x.TxBase64Body
	}
	return ""
}

type TransactionWithSign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxMessageHash string                 `protobuf:"bytes,1,opt,name=tx_message_hash,json=txMessageHash,proto3" json:"tx_message_hash,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	SignedTx      string                 `protobuf:"bytes,3,opt,name=signed_tx,json=signedTx,proto3" json:"signed_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionWithSign) Reset() {
	*x = TransactionWithSign{}
	mi := &file_dapplink_walletsign_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionWithSign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionWithSign) ProtoMessage() {}

func (x *TransactionWithSign) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionWithSign.ProtoReflect.Descriptor instead.
func (*TransactionWithSign) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{16}
}

func (x *TransactionWithSign) GetTxMessageHash() string {
	if x != nil {
		return x.TxMessageHash
	}
	return ""
}

func (x *TransactionWithSign) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransactionWithSign) GetSignedTx() string {
	if x != nil {
		return x.SignedTx
	}
	return ""
}

type BuildAndSignTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Network       string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	TxMsg         []*TransactionMessage  `protobuf:"bytes,4,rep,name=tx_msg,json=txMsg,proto3" json:"tx_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildAndSignTransactionsRequest) Reset() {
	*x = BuildAndSignTransactionsRequest{}
	mi := &file_dapplink_walletsign_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildAndSignTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildAndSignTransactionsRequest) ProtoMessage() {}

func (x *BuildAndSignTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildAndSignTransactionsRequest.ProtoReflect.Descriptor instead.
func (*BuildAndSignTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{17}
}

func (x *BuildAndSignTransactionsRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *BuildAndSignTransactionsRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *BuildAndSignTransactionsRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *BuildAndSignTransactionsRequest) GetTxMsg() []*TransactionMessage {
	if x != nil {
		return x.TxMsg
	}
	return nil
}

type BuildAndSignTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          common.ReturnCode      `protobuf:"varint,1,opt,name=code,proto3,enum=dapplink.ReturnCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TxWithSign    []*TransactionWithSign `protobuf:"bytes,3,rep,name=tx_with_sign,json=txWithSign,proto3" json:"tx_with_sign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildAndSignTransactionsResponse) Reset() {
	*x = BuildAndSignTransactionsResponse{}
	mi := &file_dapplink_walletsign_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildAndSignTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildAndSignTransactionsResponse) ProtoMessage() {}

func (x *BuildAndSignTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_walletsign_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildAndSignTransactionsResponse.ProtoReflect.Descriptor instead.
func (*BuildAndSignTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_dapplink_walletsign_proto_rawDescGZIP(), []int{18}
}

func (x *BuildAndSignTransactionsResponse) GetCode() common.ReturnCode {
	if x != nil {
		return x.Code
	}
	return common.ReturnCode(0)
}

func (x *BuildAndSignTransactionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuildAndSignTransactionsResponse) GetTxWithSign() []*TransactionWithSign {
	if x != nil {
		return x.TxWithSign
	}
	return nil
}

var File_dapplink_walletsign_proto protoreflect.FileDescriptor

const file_dapplink_walletsign_proto_rawDesc = "" +
	"\n" +
	"\x19dapplink/walletsign.proto\x12\bdapplink\x1a\x15dapplink/common.proto\"\x93\x01\n" +
	"\x16ChainSignMethodRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x04 \x01(\tR\tassetType\"~\n" +
	"\x17ChainSignMethodResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.dapplink.ReturnCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vsign_method\x18\x03 \x01(\tR\n" +
	"signMethod\"\x8f\x01\n" +
	"\x12ChainSchemaRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x04 \x01(\tR\tassetType\"q\n" +
	"\x13ChainSchemaResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.dapplink.ReturnCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06schema\x18\x03 \x01(\tR\x06schema\"`\n" +
	"\x0fExportPublicKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12.\n" +
	"\x13compress_public_key\x18\x02 \x01(\tR\x11compressPublicKey\"\x9d\x01\n" +
	"&CreateKeyPairAndExportPublicKeyRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12\x17\n" +
	"\akey_num\x18\x04 \x01(\x04R\x06keyNum\"\xb0\x01\n" +
	"'CreateKeyPairAndExportPublicKeyResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.dapplink.ReturnCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\x0fpublic_key_list\x18\x03 \x03(\v2\x19.dapplink.ExportPublicKeyR\rpublicKeyList\"\x85\x01\n" +
	"\x1aExportPublicKeyWithAddress\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12.\n" +
	"\x13compress_public_key\x18\x02 \x01(\tR\x11compressPublicKey\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\xc0\x01\n" +
	"\"CreateKeyPairsWithAddressesRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12%\n" +
	"\x0eaddress_format\x18\x04 \x01(\tR\raddressFormat\x12\x17\n" +
	"\akey_num\x18\x05 \x01(\x04R\x06keyNum\"\xc1\x01\n" +
	"#CreateKeyPairsWithAddressesResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.dapplink.ReturnCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12V\n" +
	"\x14public_key_addresses\x18\x03 \x03(\v2$.dapplink.ExportPublicKeyWithAddressR\x12publicKeyAddresses\"\xaf\x01\n" +
	"\x0fTransactionBody\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\ffrom_address\x18\x02 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12#\n" +
	"\rtoken_address\x18\x05 \x01(\tR\ftokenAddress\"\xda\x01\n" +
	"\x16SignTransactionMessage\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12!\n" +
	"\fmessage_hash\x18\x02 \x01(\tR\vmessageHash\x12\"\n" +
	"\rrisk_key_hash\x18\x03 \x01(\tR\vriskKeyHash\x12&\n" +
	"\x0fwallet_key_hash\x18\x04 \x01(\tR\rwalletKeyHash\x122\n" +
	"\atx_body\x18\x05 \x01(\v2\x19.dapplink.TransactionBodyR\x06txBody\"\xc0\x01\n" +
	"\x1eSignTransactionsMessageRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12B\n" +
	"\fsign_txn_msg\x18\x04 \x03(\v2 .dapplink.SignTransactionMessageR\n" +
	"signTxnMsg\"r\n" +
	"\x10MsgWithSignature\x12!\n" +
	"\fmessage_hash\x18\x01 \x01(\tR\vmessageHash\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"is_success\x18\x03 \x01(\bR\tisSuccess\"\xcd\x01\n" +
	"\x1fSignTransactionsMessageResponse\x12(\n" +
	"\x04Code\x18\x01 \x01(\x0e2\x14.dapplink.ReturnCodeR\x04Code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12H\n" +
	"\x12msg_with_signature\x18\x04 \x03(\v2\x1a.dapplink.MsgWithSignatureR\x10msgWithSignature\"\xa5\x01\n" +
	"\x12TransactionMessage\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12&\n" +
	"\x0fwallet_key_hash\x18\x02 \x01(\tR\rwalletKeyHash\x12\"\n" +
	"\rrisk_key_hash\x18\x03 \x01(\tR\vriskKeyHash\x12$\n" +
	"\x0etx_base64_body\x18\x04 \x01(\tR\ftxBase64Body\"s\n" +
	"\x13TransactionWithSign\x12&\n" +
	"\x0ftx_message_hash\x18\x01 \x01(\tR\rtxMessageHash\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x1b\n" +
	"\tsigned_tx\x18\x03 \x01(\tR\bsignedTx\"\xb2\x01\n" +
	"\x1fBuildAndSignTransactionsRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x123\n" +
	"\x06tx_msg\x18\x04 \x03(\v2\x1c.dapplink.TransactionMessageR\x05txMsg\"\xa7\x01\n" +
	" BuildAndSignTransactionsResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.dapplink.ReturnCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\ftx_with_sign\x18\x03 \x03(\v2\x1d.dapplink.TransactionWithSignR\n" +
	"txWithSign2\xb1\x05\n" +
	"\x11WalletSignService\x12[\n" +
	"\x12getChainSignMethod\x12 .dapplink.ChainSignMethodRequest\x1a!.dapplink.ChainSignMethodResponse\"\x00\x12O\n" +
	"\x0egetChainSchema\x12\x1c.dapplink.ChainSchemaRequest\x1a\x1d.dapplink.ChainSchemaResponse\"\x00\x12\x8a\x01\n" +
	"!createKeyPairsExportPublicKeyList\x120.dapplink.CreateKeyPairAndExportPublicKeyRequest\x1a1.dapplink.CreateKeyPairAndExportPublicKeyResponse\"\x00\x12|\n" +
	"\x1bcreateKeyPairsWithAddresses\x12,.dapplink.CreateKeyPairsWithAddressesRequest\x1a-.dapplink.CreateKeyPairsWithAddressesResponse\"\x00\x12p\n" +
	"\x17signTransactionsMessage\x12(.dapplink.SignTransactionsMessageRequest\x1a).dapplink.SignTransactionsMessageResponse\"\x00\x12q\n" +
	"\x18buildAndSignTransactions\x12).dapplink.BuildAndSignTransactionsRequest\x1a*.dapplink.BuildAndSignTransactionsResponseB\x18Z\x16../protobuf/walletsignb\x06proto3"

var (
	file_dapplink_walletsign_proto_rawDescOnce sync.Once
	file_dapplink_walletsign_proto_rawDescData []byte
)

func file_dapplink_walletsign_proto_rawDescGZIP() []byte {
	file_dapplink_walletsign_proto_rawDescOnce.Do(func() {
		file_dapplink_walletsign_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dapplink_walletsign_proto_rawDesc), len(file_dapplink_walletsign_proto_rawDesc)))
	})
	return file_dapplink_walletsign_proto_rawDescData
}

var file_dapplink_walletsign_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_dapplink_walletsign_proto_goTypes = []any{
	(*ChainSignMethodRequest)(nil),                  // 0: dapplink.ChainSignMethodRequest
	(*ChainSignMethodResponse)(nil),                 // 1: dapplink.ChainSignMethodResponse
	(*ChainSchemaRequest)(nil),                      // 2: dapplink.ChainSchemaRequest
	(*ChainSchemaResponse)(nil),                     // 3: dapplink.ChainSchemaResponse
	(*ExportPublicKey)(nil),                         // 4: dapplink.ExportPublicKey
	(*CreateKeyPairAndExportPublicKeyRequest)(nil),  // 5: dapplink.CreateKeyPairAndExportPublicKeyRequest
	(*CreateKeyPairAndExportPublicKeyResponse)(nil), // 6: dapplink.CreateKeyPairAndExportPublicKeyResponse
	(*ExportPublicKeyWithAddress)(nil),              // 7: dapplink.ExportPublicKeyWithAddress
	(*CreateKeyPairsWithAddressesRequest)(nil),      // 8: dapplink.CreateKeyPairsWithAddressesRequest
	(*CreateKeyPairsWithAddressesResponse)(nil),     // 9: dapplink.CreateKeyPairsWithAddressesResponse
	(*TransactionBody)(nil),                         // 10: dapplink.TransactionBody
	(*SignTransactionMessage)(nil),                  // 11: dapplink.SignTransactionMessage
	(*SignTransactionsMessageRequest)(nil),          // 12: dapplink.SignTransactionsMessageRequest
	(*MsgWithSignature)(nil),                        // 13: dapplink.MsgWithSignature
	(*SignTransactionsMessageResponse)(nil),         // 14: dapplink.SignTransactionsMessageResponse
	(*TransactionMessage)(nil),                      // 15: dapplink.TransactionMessage
	(*TransactionWithSign)(nil),                     // 16: dapplink.TransactionWithSign
	(*BuildAndSignTransactionsRequest)(nil),         // 17: dapplink.BuildAndSignTransactionsRequest
	(*BuildAndSignTransactionsResponse)(nil),        // 18: dapplink.BuildAndSignTransactionsResponse
	(common.ReturnCode)(0),                          // 19: dapplink.ReturnCode
}
var file_dapplink_walletsign_proto_depIdxs = []int32{
	19, // 0: dapplink.ChainSignMethodResponse.code:type_name -> dapplink.ReturnCode
	19, // 1: dapplink.ChainSchemaResponse.code:type_name -> dapplink.ReturnCode
	19, // 2: dapplink.CreateKeyPairAndExportPublicKeyResponse.code:type_name -> dapplink.ReturnCode
	4,  // 3: dapplink.CreateKeyPairAndExportPublicKeyResponse.public_key_list:type_name -> dapplink.ExportPublicKey
	19, // 4: dapplink.CreateKeyPairsWithAddressesResponse.code:type_name -> dapplink.ReturnCode
	7,  // 5: dapplink.CreateKeyPairsWithAddressesResponse.public_key_addresses:type_name -> dapplink.ExportPublicKeyWithAddress
	10, // 6: dapplink.SignTransactionMessage.tx_body:type_name -> dapplink.TransactionBody
	11, // 7: dapplink.SignTransactionsMessageRequest.sign_txn_msg:type_name -> dapplink.SignTransactionMessage
	19, // 8: dapplink.SignTransactionsMessageResponse.Code:type_name -> dapplink.ReturnCode
	13, // 9: dapplink.SignTransactionsMessageResponse.msg_with_signature:type_name -> dapplink.MsgWithSignature
	15, // 10: dapplink.BuildAndSignTransactionsRequest.tx_msg:type_name -> dapplink.TransactionMessage
	19, // 11: dapplink.BuildAndSignTransactionsResponse.code:type_name -> dapplink.ReturnCode
	16, // 12: dapplink.BuildAndSignTransactionsResponse.tx_with_sign:type_name -> dapplink.TransactionWithSign
	0,  // 13: dapplink.WalletSignService.getChainSignMethod:input_type -> dapplink.ChainSignMethodRequest
	2,  // 14: dapplink.WalletSignService.getChainSchema:input_type -> dapplink.ChainSchemaRequest
	5,  // 15: dapplink.WalletSignService.createKeyPairsExportPublicKeyList:input_type -> dapplink.CreateKeyPairAndExportPublicKeyRequest
	8,  // 16: dapplink.WalletSignService.createKeyPairsWithAddresses:input_type -> dapplink.CreateKeyPairsWithAddressesRequest
	12, // 17: dapplink.WalletSignService.signTransactionsMessage:input_type -> dapplink.SignTransactionsMessageRequest
	17, // 18: dapplink.WalletSignService.buildAndSignTransactions:input_type -> dapplink.BuildAndSignTransactionsRequest
	1,  // 19: dapplink.WalletSignService.getChainSignMethod:output_type -> dapplink.ChainSignMethodResponse
	3,  // 20: dapplink.WalletSignService.getChainSchema:output_type -> dapplink.ChainSchemaResponse
	6,  // 21: dapplink.WalletSignService.createKeyPairsExportPublicKeyList:output_type -> dapplink.CreateKeyPairAndExportPublicKeyResponse
	9,  // 22: dapplink.WalletSignService.createKeyPairsWithAddresses:output_type -> dapplink.CreateKeyPairsWithAddressesResponse
	14, // 23: dapplink.WalletSignService.signTransactionsMessage:output_type -> dapplink.SignTransactionsMessageResponse
	18, // 24: dapplink.WalletSignService.buildAndSignTransactions:output_type -> dapplink.BuildAndSignTransactionsResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_dapplink_walletsign_proto_init() }
func file_dapplink_walletsign_proto_init() {
	if File_dapplink_walletsign_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dapplink_walletsign_proto_rawDesc), len(file_dapplink_walletsign_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dapplink_walletsign_proto_goTypes,
		DependencyIndexes: file_dapplink_walletsign_proto_depIdxs,
		MessageInfos:      file_dapplink_walletsign_proto_msgTypes,
	}.Build()
	File_dapplink_walletsign_proto = out.File
	file_dapplink_walletsign_proto_goTypes = nil
	file_dapplink_walletsign_proto_depIdxs = nil
}
