// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: dapplink/wallerpcservice.proto

package dapplinkwallet

import (
	"github.com/dapplink-labs/dapplink-wallet-api/protobuf/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// type in (eoa hot cold)
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_dapplink_wallerpcservice_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decimals      uint32                 `protobuf:"varint,1,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TokenName     string                 `protobuf:"bytes,3,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	CollectAmount string                 `protobuf:"bytes,4,opt,name=collect_amount,json=collectAmount,proto3" json:"collect_amount,omitempty"`
	ColdAmount    string                 `protobuf:"bytes,5,opt,name=cold_amount,json=coldAmount,proto3" json:"cold_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_dapplink_wallerpcservice_proto_rawDescGZIP(), []int{1}
}

func (x *Token) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *Token) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Token) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *Token) GetCollectAmount() string {
	if x != nil {
		return x.CollectAmount
	}
	return ""
}

func (x *Token) GetColdAmount() string {
	if x != nil {
		return x.ColdAmount
	}
	return ""
}

type BusinessRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NotifyUrl     string                 `protobuf:"bytes,3,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessRegisterRequest) Reset() {
	*x = BusinessRegisterRequest{}
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessRegisterRequest) ProtoMessage() {}

func (x *BusinessRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessRegisterRequest.ProtoReflect.Descriptor instead.
func (*BusinessRegisterRequest) Descriptor() ([]byte, []int) {
	return file_dapplink_wallerpcservice_proto_rawDescGZIP(), []int{2}
}

func (x *BusinessRegisterRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *BusinessRegisterRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BusinessRegisterRequest) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

type BusinessRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          common.ReturnCode      `protobuf:"varint,1,opt,name=Code,proto3,enum=dapplink.ReturnCode" json:"Code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessRegisterResponse) Reset() {
	*x = BusinessRegisterResponse{}
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessRegisterResponse) ProtoMessage() {}

func (x *BusinessRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessRegisterResponse.ProtoReflect.Descriptor instead.
func (*BusinessRegisterResponse) Descriptor() ([]byte, []int) {
	return file_dapplink_wallerpcservice_proto_rawDescGZIP(), []int{3}
}

func (x *BusinessRegisterResponse) GetCode() common.ReturnCode {
	if x != nil {
		return x.Code
	}
	return common.ReturnCode(0)
}

func (x *BusinessRegisterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ExportAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PublicKeys    []*common.PublicKey    `protobuf:"bytes,3,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAddressesRequest) Reset() {
	*x = ExportAddressesRequest{}
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAddressesRequest) ProtoMessage() {}

func (x *ExportAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAddressesRequest.ProtoReflect.Descriptor instead.
func (*ExportAddressesRequest) Descriptor() ([]byte, []int) {
	return file_dapplink_wallerpcservice_proto_rawDescGZIP(), []int{4}
}

func (x *ExportAddressesRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *ExportAddressesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExportAddressesRequest) GetPublicKeys() []*common.PublicKey {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

type ExportAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          common.ReturnCode      `protobuf:"varint,1,opt,name=Code,proto3,enum=dapplink.ReturnCode" json:"Code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAddressesResponse) Reset() {
	*x = ExportAddressesResponse{}
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAddressesResponse) ProtoMessage() {}

func (x *ExportAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAddressesResponse.ProtoReflect.Descriptor instead.
func (*ExportAddressesResponse) Descriptor() ([]byte, []int) {
	return file_dapplink_wallerpcservice_proto_rawDescGZIP(), []int{5}
}

func (x *ExportAddressesResponse) GetCode() common.ReturnCode {
	if x != nil {
		return x.Code
	}
	return common.ReturnCode(0)
}

func (x *ExportAddressesResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ExportAddressesResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type WithdrawTxn struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ChainId         string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	From            string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To              string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Value           string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	ContractAddress string                 `protobuf:"bytes,6,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	TokenId         string                 `protobuf:"bytes,7,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenMeta       string                 `protobuf:"bytes,8,opt,name=token_meta,json=tokenMeta,proto3" json:"token_meta,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WithdrawTxn) Reset() {
	*x = WithdrawTxn{}
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawTxn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawTxn) ProtoMessage() {}

func (x *WithdrawTxn) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawTxn.ProtoReflect.Descriptor instead.
func (*WithdrawTxn) Descriptor() ([]byte, []int) {
	return file_dapplink_wallerpcservice_proto_rawDescGZIP(), []int{6}
}

func (x *WithdrawTxn) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WithdrawTxn) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *WithdrawTxn) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *WithdrawTxn) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *WithdrawTxn) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *WithdrawTxn) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *WithdrawTxn) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *WithdrawTxn) GetTokenMeta() string {
	if x != nil {
		return x.TokenMeta
	}
	return ""
}

type WithdrawTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	WithdrawTxn   []*WithdrawTxn         `protobuf:"bytes,2,rep,name=withdraw_txn,json=withdrawTxn,proto3" json:"withdraw_txn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawTransactionRequest) Reset() {
	*x = WithdrawTransactionRequest{}
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawTransactionRequest) ProtoMessage() {}

func (x *WithdrawTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawTransactionRequest.ProtoReflect.Descriptor instead.
func (*WithdrawTransactionRequest) Descriptor() ([]byte, []int) {
	return file_dapplink_wallerpcservice_proto_rawDescGZIP(), []int{7}
}

func (x *WithdrawTransactionRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *WithdrawTransactionRequest) GetWithdrawTxn() []*WithdrawTxn {
	if x != nil {
		return x.WithdrawTxn
	}
	return nil
}

type WithdrawTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          common.ReturnCode      `protobuf:"varint,1,opt,name=code,proto3,enum=dapplink.ReturnCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawTransactionResponse) Reset() {
	*x = WithdrawTransactionResponse{}
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawTransactionResponse) ProtoMessage() {}

func (x *WithdrawTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawTransactionResponse.ProtoReflect.Descriptor instead.
func (*WithdrawTransactionResponse) Descriptor() ([]byte, []int) {
	return file_dapplink_wallerpcservice_proto_rawDescGZIP(), []int{8}
}

func (x *WithdrawTransactionResponse) GetCode() common.ReturnCode {
	if x != nil {
		return x.Code
	}
	return common.ReturnCode(0)
}

func (x *WithdrawTransactionResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SetTokenAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TokenList     []*Token               `protobuf:"bytes,2,rep,name=token_list,json=tokenList,proto3" json:"token_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTokenAddressRequest) Reset() {
	*x = SetTokenAddressRequest{}
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTokenAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTokenAddressRequest) ProtoMessage() {}

func (x *SetTokenAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTokenAddressRequest.ProtoReflect.Descriptor instead.
func (*SetTokenAddressRequest) Descriptor() ([]byte, []int) {
	return file_dapplink_wallerpcservice_proto_rawDescGZIP(), []int{9}
}

func (x *SetTokenAddressRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SetTokenAddressRequest) GetTokenList() []*Token {
	if x != nil {
		return x.TokenList
	}
	return nil
}

type SetTokenAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          common.ReturnCode      `protobuf:"varint,1,opt,name=code,proto3,enum=dapplink.ReturnCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTokenAddressResponse) Reset() {
	*x = SetTokenAddressResponse{}
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTokenAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTokenAddressResponse) ProtoMessage() {}

func (x *SetTokenAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapplink_wallerpcservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTokenAddressResponse.ProtoReflect.Descriptor instead.
func (*SetTokenAddressResponse) Descriptor() ([]byte, []int) {
	return file_dapplink_wallerpcservice_proto_rawDescGZIP(), []int{10}
}

func (x *SetTokenAddressResponse) GetCode() common.ReturnCode {
	if x != nil {
		return x.Code
	}
	return common.ReturnCode(0)
}

func (x *SetTokenAddressResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_dapplink_wallerpcservice_proto protoreflect.FileDescriptor

const file_dapplink_wallerpcservice_proto_rawDesc = "" +
	"\n" +
	"\x1edapplink/wallerpcservice.proto\x12\bdapplink\x1a\x15dapplink/common.proto\"7\n" +
	"\aAddress\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xa4\x01\n" +
	"\x05Token\x12\x1a\n" +
	"\bdecimals\x18\x01 \x01(\rR\bdecimals\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"token_name\x18\x03 \x01(\tR\ttokenName\x12%\n" +
	"\x0ecollect_amount\x18\x04 \x01(\tR\rcollectAmount\x12\x1f\n" +
	"\vcold_amount\x18\x05 \x01(\tR\n" +
	"coldAmount\"~\n" +
	"\x17BusinessRegisterRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x03 \x01(\tR\tnotifyUrl\"V\n" +
	"\x18BusinessRegisterResponse\x12(\n" +
	"\x04Code\x18\x01 \x01(\x0e2\x14.dapplink.ReturnCodeR\x04Code\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"\x94\x01\n" +
	"\x16ExportAddressesRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x124\n" +
	"\vpublic_keys\x18\x03 \x03(\v2\x13.dapplink.PublicKeyR\n" +
	"publicKeys\"\x86\x01\n" +
	"\x17ExportAddressesResponse\x12(\n" +
	"\x04Code\x18\x01 \x01(\x0e2\x14.dapplink.ReturnCodeR\x04Code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12/\n" +
	"\taddresses\x18\x03 \x03(\v2\x11.dapplink.AddressR\taddresses\"\xe6\x01\n" +
	"\vWithdrawTxn\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12)\n" +
	"\x10contract_address\x18\x06 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\a \x01(\tR\atokenId\x12\x1d\n" +
	"\n" +
	"token_meta\x18\b \x01(\tR\ttokenMeta\"}\n" +
	"\x1awithdrawTransactionRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x128\n" +
	"\fwithdraw_txn\x18\x02 \x03(\v2\x15.dapplink.WithdrawTxnR\vwithdrawTxn\"Y\n" +
	"\x1bwithdrawTransactionResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.dapplink.ReturnCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"g\n" +
	"\x16SetTokenAddressRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12.\n" +
	"\n" +
	"token_list\x18\x02 \x03(\v2\x0f.dapplink.TokenR\ttokenList\"U\n" +
	"\x17SetTokenAddressResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.dapplink.ReturnCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\x9f\x03\n" +
	"\x1aBusinessMiddleWireServices\x12[\n" +
	"\x10businessRegister\x12!.dapplink.BusinessRegisterRequest\x1a\".dapplink.BusinessRegisterResponse\"\x00\x12X\n" +
	"\x0fsetTokenAddress\x12 .dapplink.SetTokenAddressRequest\x1a!.dapplink.SetTokenAddressResponse\"\x00\x12d\n" +
	"\x1bexportAddressesByPublicKeys\x12 .dapplink.ExportAddressesRequest\x1a!.dapplink.ExportAddressesResponse\"\x00\x12d\n" +
	"\x13withdrawTransaction\x12$.dapplink.withdrawTransactionRequest\x1a%.dapplink.withdrawTransactionResponse\"\x00B\x1cZ\x1a../protobuf/dapplinkwalletb\x06proto3"

var (
	file_dapplink_wallerpcservice_proto_rawDescOnce sync.Once
	file_dapplink_wallerpcservice_proto_rawDescData []byte
)

func file_dapplink_wallerpcservice_proto_rawDescGZIP() []byte {
	file_dapplink_wallerpcservice_proto_rawDescOnce.Do(func() {
		file_dapplink_wallerpcservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dapplink_wallerpcservice_proto_rawDesc), len(file_dapplink_wallerpcservice_proto_rawDesc)))
	})
	return file_dapplink_wallerpcservice_proto_rawDescData
}

var file_dapplink_wallerpcservice_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_dapplink_wallerpcservice_proto_goTypes = []any{
	(*Address)(nil),                     // 0: dapplink.Address
	(*Token)(nil),                       // 1: dapplink.Token
	(*BusinessRegisterRequest)(nil),     // 2: dapplink.BusinessRegisterRequest
	(*BusinessRegisterResponse)(nil),    // 3: dapplink.BusinessRegisterResponse
	(*ExportAddressesRequest)(nil),      // 4: dapplink.ExportAddressesRequest
	(*ExportAddressesResponse)(nil),     // 5: dapplink.ExportAddressesResponse
	(*WithdrawTxn)(nil),                 // 6: dapplink.WithdrawTxn
	(*WithdrawTransactionRequest)(nil),  // 7: dapplink.withdrawTransactionRequest
	(*WithdrawTransactionResponse)(nil), // 8: dapplink.withdrawTransactionResponse
	(*SetTokenAddressRequest)(nil),      // 9: dapplink.SetTokenAddressRequest
	(*SetTokenAddressResponse)(nil),     // 10: dapplink.SetTokenAddressResponse
	(common.ReturnCode)(0),              // 11: dapplink.ReturnCode
	(*common.PublicKey)(nil),            // 12: dapplink.PublicKey
}
var file_dapplink_wallerpcservice_proto_depIdxs = []int32{
	11, // 0: dapplink.BusinessRegisterResponse.Code:type_name -> dapplink.ReturnCode
	12, // 1: dapplink.ExportAddressesRequest.public_keys:type_name -> dapplink.PublicKey
	11, // 2: dapplink.ExportAddressesResponse.Code:type_name -> dapplink.ReturnCode
	0,  // 3: dapplink.ExportAddressesResponse.addresses:type_name -> dapplink.Address
	6,  // 4: dapplink.withdrawTransactionRequest.withdraw_txn:type_name -> dapplink.WithdrawTxn
	11, // 5: dapplink.withdrawTransactionResponse.code:type_name -> dapplink.ReturnCode
	1,  // 6: dapplink.SetTokenAddressRequest.token_list:type_name -> dapplink.Token
	11, // 7: dapplink.SetTokenAddressResponse.code:type_name -> dapplink.ReturnCode
	2,  // 8: dapplink.BusinessMiddleWireServices.businessRegister:input_type -> dapplink.BusinessRegisterRequest
	9,  // 9: dapplink.BusinessMiddleWireServices.setTokenAddress:input_type -> dapplink.SetTokenAddressRequest
	4,  // 10: dapplink.BusinessMiddleWireServices.exportAddressesByPublicKeys:input_type -> dapplink.ExportAddressesRequest
	7,  // 11: dapplink.BusinessMiddleWireServices.withdrawTransaction:input_type -> dapplink.withdrawTransactionRequest
	3,  // 12: dapplink.BusinessMiddleWireServices.businessRegister:output_type -> dapplink.BusinessRegisterResponse
	10, // 13: dapplink.BusinessMiddleWireServices.setTokenAddress:output_type -> dapplink.SetTokenAddressResponse
	5,  // 14: dapplink.BusinessMiddleWireServices.exportAddressesByPublicKeys:output_type -> dapplink.ExportAddressesResponse
	8,  // 15: dapplink.BusinessMiddleWireServices.withdrawTransaction:output_type -> dapplink.withdrawTransactionResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_dapplink_wallerpcservice_proto_init() }
func file_dapplink_wallerpcservice_proto_init() {
	if File_dapplink_wallerpcservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dapplink_wallerpcservice_proto_rawDesc), len(file_dapplink_wallerpcservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dapplink_wallerpcservice_proto_goTypes,
		DependencyIndexes: file_dapplink_wallerpcservice_proto_depIdxs,
		MessageInfos:      file_dapplink_wallerpcservice_proto_msgTypes,
	}.Build()
	File_dapplink_wallerpcservice_proto = out.File
	file_dapplink_wallerpcservice_proto_goTypes = nil
	file_dapplink_wallerpcservice_proto_depIdxs = nil
}
